# -*- coding: utf-8 -*-
"""starcoder_data_processor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxip08hnAT-II_5bHPr2-GS9T5TMq7wX
"""

!pip install transformers torch pandas

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import pandas as pd


model_name = "bigcode/starcoder2-3b"

print("Loading model...")

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer
)


task = """
Write a Python function that:
1. Reads data from a CSV file named transactions.csv
2. Filters transactions where Amount > 10000
3. Prints the filtered transactions
4. Prints total number of filtered transactions
5. Prints total amount of filtered transactions
"""


prompt = f"""
# Python Task
{task}

# Python Code
"""

print("\nGenerating code...\n")

response = generator(
    prompt,
    max_new_tokens=250,
    temperature=0.2,
    do_sample=True
)

generated_code = response[0]["generated_text"]

print("Generated Code:\n")
print(generated_code)


print("\nExecuting required data processing...\n")


df = pd.read_csv("transactions.csv")

filtered_df = df[df["Amount"] > 10000]

print("Filtered Transactions Above Rs10000:\n")
print(filtered_df)

print("\nSummary:")
print("Total Transactions:", len(filtered_df))
print("Total Amount:", filtered_df["Amount"].sum())


filtered_df.to_csv("filtered_transactions.csv", index=False)

print("\nFiltered CSV saved as filtered_transactions.csv")